# Enable True Color (24-bit RGB) for Neovim themes
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
set -g default-terminal "screen-256color"

bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"

# Switch windows with Alt+h and Alt+l (No Prefix)
bind -n M-h previous-window
bind -n M-l next-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'vaaleyard/tmux-dotbar'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

